# Compare different Nash equilibrium solvers
1. time
2. success rate

In [7]:
from equilibrium_solver import *
import numpy as np
import time

In [11]:
itr = 100  # number of test matrices
matrix_size = (6, 6)
t_list=[]
fail_list=[]

solvers = [NashEquilibriaSolver, NashEquilibriumSolver, NashEquilibriumLPSolver, NashEquilibriumCVXPYSolver, NashEquilibriumGUROBISolver, NashEquilibriumECOSSolver]
# print(solvers)

# generate random matrices for test
rand_matrices=[np.array(np.random.uniform(-1, 1, matrix_size)) for _ in range(itr)]

for solver in solvers:
    t0 = time.time()
    fail = 0.
    for i in range(itr):
        try:
            solver(rand_matrices[i])
        except:  # TODO this is not accurate since sometimes it returns wrong results but no error
            # print(rand_matrices[i])
            fail+=1
    t1=time.time()
    t_list.append((t1-t0)/itr)
    fail_list.append(fail/itr)

solvers = [s.__name__ for s in solvers]
results = {'Solver': solvers, 'Time': t_list, 'Failure rate': fail_list}
import pandas as pd
df = pd.DataFrame(results)
print(df)

/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/pulp/pulp.py:1711: UserWarning: Overwriting previously set objective.
  warnings.warn("Overwriting previously set objective.")


                        Solver      Time  Failure rate
0         NashEquilibriaSolver  0.208456          0.00
1        NashEquilibriumSolver  0.000571          0.00
2      NashEquilibriumLPSolver  0.013513          0.00
3   NashEquilibriumCVXPYSolver  0.003935          0.00
4  NashEquilibriumGUROBISolver  0.000951          0.14
5    NashEquilibriumECOSSolver  0.000384          0.00


/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/ecos/ecos.py:26: UserWarning: Converting G to a CSC matrix; may take a while.
  warn("Converting G to a CSC matrix; may take a while.")
/home/quantumiracle/anaconda3/envs/x/lib/python3.7/site-packages/ecos/ecos.py:29: UserWarning: Converting A to a CSC matrix; may take a while.
  warn("Converting A to a CSC matrix; may take a while.")


In [13]:
# Gurobi solver does not work in all cases
import numpy as np
matrix_size = (6, 6)
# a=np.array([[ 0.036,  0.023,  0.042,  0.001, -0.002, -0.029],
#  [ 0.031, -0.026,  0.062, -0.034,  0.017, -0.043],
#  [ 0.004, -0.011, -0.026, -0.066, -0.008, -0.031],
#  [-0.03,  -0.032,  0.032, -0.026,  0.01,   0.001],
#  [-0.009,  0.042,  0.047, -0.023, -0.03,  -0.001],
#  [ 0.024,  0.034,  0.017,  0.017, -0.043, -0.061]])
# print(np.linalg.det(a))
a=np.array([[95, 97], [97, 97]])
NashEquilibriumGUROBISolver(a)

for i in range(20):
    print(i)
    a=np.array(np.random.uniform(-1, 1, matrix_size))
    print(np.linalg.det(a))
    try:
        NashEquilibriumGUROBISolver(a)
    except:
        print('Not solved matrix: ', a)

0
-0.21943068402422208
1
0.11823117232687501
2
0.42183561498487365
3
1.2118251625908834
4
-1.1603927897100847
5
-3.4270418308104977
6
-0.778322127602816
7
-0.1724547018305776
8
-0.13103288229400437
9
0.825318321187979
10
1.5512597820907925
11
-0.32914406881714847
12
-0.36389052891648854
13
0.01209214350701601
14
1.2707624912505255
15
0.40887028507482226
Not solved matrix:  [[-0.41301346  0.03481041 -0.12241227  0.63579532  0.1566146   0.47455712]
 [-0.9480402   0.79097008 -0.86289357  0.05175797  0.24760642  0.65818024]
 [-0.79550654  0.590004    0.2312181   0.52699437  0.24746801  0.89843936]
 [-0.53679791  0.68036029 -0.57018641  0.49281511 -0.02027984 -0.02856437]
 [-0.86130637  0.33901386  0.88523092 -0.93055369 -0.03208438  0.40901916]
 [-0.65256575  0.30034441 -0.97946958 -0.70661677 -0.65086773  0.96750481]]
16
0.5341072191627828
17
-0.4509151694470714
18
0.6301634837120715
19
-0.6740257502476832
