# Compare different Nash equilibrium solvers
1. time
2. success rate

In [4]:
# from eq_solver import NashEquilibriaSolver, NashEquilibriumSolver
# from eq_LPsolver import NashEquilibriumLPSolver, CoarseCorrelatedEquilibriumLPSolver
# from eq_CVXPYsolver import NashEquilibriumCVXPYSolver
# from eq_GUROBIsolver import NashEquilibriumGUROBISolver
# from eq_ECOSsolver import NashEquilibriumECOSSolver
from equilibrium_solver import *

solvers = [NashEquilibriaSolver, NashEquilibriumSolver, NashEquilibriumLPSolver, NashEquilibriumCVXPYSolver, NashEquilibriumGUROBISolver, NashEquilibriumECOSSolver]
print(solvers)


ModuleNotFoundError: No module named 'eq_CVXPYsolver'

In [5]:
import numpy as np
import time
itr = 100
matrix_size = (6, 6)
t_list=[]
fail_list=[]
# generate random matrices for test
rand_matrices=[np.array(np.random.uniform(-1, 1, matrix_size)) for _ in range(itr)]

for solver in solvers:
    print(solver)
    t0 = time.time()
    fail = 0.
    for i in range(itr):
        print(i)
        try:
            solver(rand_matrices[i])
        except:  # TODO this is not accurate since sometimes it returns wrong results but no error
            print(rand_matrices[i])
            fail+=1
    t1=time.time()
    t_list.append((t1-t0)/itr)
    fail_list.append(fail/itr)
print(solvers)
print(t_list)
print(fail_list)

<function NashEquilibriaSolver at 0x7fb5a412d620>
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
<function NashEquilibriumSolver at 0x7fb543ed0f28>
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
<function NashEquilibriumLPSolver at 0x7fb543e810d0>
0


/home/quantumiracle/.conda/envs/robo/lib/python3.6/site-packages/pulp/pulp.py:1544: UserWarning: Overwriting previously set objective.
  warnings.warn("Overwriting previously set objective.")


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
<function NashEquilibriumCVXPYSolver at 0x7fb543af4268>
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
<function NashEquilibriumGUROBISolver at 0x7fb542a4f7b8>
0
1
2
3
4
5
[[ 0.48489836 -0.00894116  0.69453607 -0.15441212 -0.91742776  0.28642625]
 [-0.6796644  -0.76773429  0.46953842 -0.02905713  0.2283287   0.07606151]
 [ 0.50677235 -0.04275736 -0.07499591 -0.38340924  0.06993108  0.09007517]
 [ 0.39895104 -0.2807928   0.74225635 -0.75637177 -0.59714962 -0.7611988


ECOS 2.0.7 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  +5.300e-02  -6.823e+00  +4e+01  6e-01  1e+00  1e+00  2e+00    ---    ---    1  1  - |  -  - 
 1  +8.382e-02  -2.115e-01  +8e+00  7e-02  3e-01  8e-01  7e-01  0.8252  2e-01   1  1  1 |  0  0
 2  +9.507e-02  +5.742e-02  +1e+00  8e-03  3e-02  8e-02  9e-02  0.8865  1e-02   1  1  1 |  0  0
 3  +1.013e-01  +9.908e-02  +5e-02  3e-04  1e-03  3e-03  4e-03  0.9713  1e-02   1  1  1 |  0  0
 4  +1.019e-01  +1.018e-01  +5e-04  4e-06  1e-05  3e-05  4e-05  0.9890  1e-04   1  1  1 |  0  0
 5  +1.019e-01  +1.019e-01  +6e-06  4e-08  1e-07  4e-07  5e-07  0.9890  1e-04   1  1  1 |  0  0
 6  +1.019e-01  +1.019e-01  +7e-08  5e-10  2e-09  4e-09  5e-09  0.9890  1e-04   1  0  0 |  0  0
 7  +1.019e-01  +1.019e-01  +7e-10  5e-12  2e-11  4e-11  6e-11  0.9890  1e-04   1  0  0 |  0  0

OPTIMAL (within feastol=1.7e-11, reltol=7.3e-

/home/quantumiracle/.conda/envs/robo/lib/python3.6/site-packages/ecos/ecos.py:26: UserWarning: Converting G to a CSC matrix; may take a while.
  warn("Converting G to a CSC matrix; may take a while.")
/home/quantumiracle/.conda/envs/robo/lib/python3.6/site-packages/ecos/ecos.py:29: UserWarning: Converting A to a CSC matrix; may take a while.
  warn("Converting A to a CSC matrix; may take a while.")


In [14]:
# Gurobi solver does not work in all cases
import numpy as np
matrix_size = (6, 6)
# a=np.array([[ 0.036,  0.023,  0.042,  0.001, -0.002, -0.029],
#  [ 0.031, -0.026,  0.062, -0.034,  0.017, -0.043],
#  [ 0.004, -0.011, -0.026, -0.066, -0.008, -0.031],
#  [-0.03,  -0.032,  0.032, -0.026,  0.01,   0.001],
#  [-0.009,  0.042,  0.047, -0.023, -0.03,  -0.001],
#  [ 0.024,  0.034,  0.017,  0.017, -0.043, -0.061]])
# print(np.linalg.det(a))
a=np.array([[95, 97], [97, 97]])
NashEquilibriumGUROBISolver(a)

for i in range(20):
    print(i)
    a=np.array(np.random.uniform(-1, 1, matrix_size))
    print(np.linalg.det(a))
    NashEquilibriumGUROBISolver(a)

([0.0, 1.0], [1.0, 0.0])